version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type:build"
    open-pull-requests-limit: 3
    rebase-strategy: "disabled"
    commit-message:
      prefix: "build"
      include: "scope"
    assignees:
      - "beep-boop-ci"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "type:build"
    open-pull-requests-limit: 10
    rebase-strategy: "disabled"
    commit-message:
      prefix: "build"
      include: "scope"
    ignore:
      - dependency-name: "boto3"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "pre-commit"
        update-types: ["version-update:semver-patch"]
    assignees:
      - "beep-boop-ci"
