name: PR CI - Django API

on:
  pull_request:
    paths-ignore:
      - 'modal_app/**'
  push:
    branches:
      - main
    paths-ignore:
      - 'modal_app/**'
  workflow_call:

jobs:
  check_migrations:
    name: Check Migrations
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: ci
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pipenv
          pipenv requirements --dev > requirements.txt
          pip install -r requirements.txt

      - name: Check for missing migrations
        run: python manage.py makemigrations --check --dry-run

      - name: Run fake migrations
        run: python manage.py migrate --fake --noinput

  lint:
    name: Lint
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: ci
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pipenv
          pipenv requirements --dev > requirements.txt
          pip install -r requirements.txt

      - name: Run linting (ruff)
        run: ruff check .

  test:
    name: Test
    needs: check_migrations
    runs-on: ubuntu-latest
    env:
      DJANGO_ENV: test
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel pipenv
          pipenv requirements --dev > requirements.txt
          pip install -r requirements.txt

      - name: Run tests
        run: python manage.py test
        timeout-minutes: 10
